export const SET_PRODUCTS_DATA = "SET_PRODUCTS_DATA"
export const SET_PRODUCTS_DATA_LOADING = "SET_PRODUCTS_DATA_LOADING"
export const SET_PRODUCTS_DATA_LOADING_ERROR = "SET_PRODUCTS_DATA_LOADING_ERROR"